# Generated by Django 3.2.13 on 2022-07-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='prod', max_length=255),
            preserve_default=False,
        ),
    ]
