from enum import Enum




class AuthPermEnum(Enum):
	# USER PERMISSIONS
	USER_CREATE = 'USER_CREATE'
	USER_UPDATE = 'USER_UPDATE'
	USER_PARTIAL_UPDATE = 'USER_PARTIAL_UPDATE'
	USER_DELETE = 'USER_DELETE'
	USER_LIST = 'USER_LIST'
	USER_DETAILS = 'USER_DETAILS'

	# VENDOR PERMISSIONS
	VENDOR_CREATE = 'VENDOR_CREATE'
	VENDOR_UPDATE = 'VENDOR_UPDATE'
	VENDOR_PARTIAL_UPDATE = 'VENDOR_PARTIAL_UPDATE'
	VENDOR_DELETE = 'VENDOR_DELETE'
	VENDOR_LIST = 'VENDOR_LIST'
	VENDOR_DETAILS = 'VENDOR_DETAILS'

	# CUSTOMER PERMISSIONS
	CUSTOMER_CREATE = 'CUSTOMER_CREATE'
	CUSTOMER_UPDATE = 'CUSTOMER_UPDATE'
	CUSTOMER_PARTIAL_UPDATE = 'CUSTOMER_PARTIAL_UPDATE'
	CUSTOMER_DELETE = 'CUSTOMER_DELETE'
	CUSTOMER_LIST = 'CUSTOMER_LIST'
	CUSTOMER_DETAILS = 'CUSTOMER_DETAILS'

	# PERMISSION PERMISSIONS
	PERMISSION_CREATE = 'PERMISSION_CREATE'
	PERMISSION_UPDATE = 'PERMISSION_UPDATE'
	PERMISSION_PARTIAL_UPDATE = 'PERMISSION_PARTIAL_UPDATE'
	PERMISSION_DELETE = 'PERMISSION_DELETE'
	PERMISSION_LIST = 'PERMISSION_LIST'
	PERMISSION_DETAILS = 'PERMISSION_DETAILS'

	# ROLE PERMISSION
	ROLE_CREATE = 'ROLE_CREATE'
	ROLE_UPDATE = 'ROLE_UPDATE'
	ROLE_DELETE = 'ROLE_DELETE'
	ROLE_LIST = 'ROLE_LIST'
	ROLE_DETAILS = 'ROLE_DETAILS'

	# COUNTRY PERMISSION
	COUNTRY_CREATE = 'COUNTRY_CREATE'
	COUNTRY_UPDATE = 'COUNTRY_UPDATE'
	COUNTRY_DELETE = 'COUNTRY_DELETE'
	COUNTRY_LIST = 'COUNTRY_LIST'
	COUNTRY_DETAILS = 'COUNTRY_DETAILS'




class ProductPermEnum(Enum):

	# WEATHER_TYPE PERMISSION
	WEATHER_TYPE_CREATE = 'WEATHER_TYPE_CREATE'
	WEATHER_TYPE_UPDATE = 'WEATHER_TYPE_UPDATE'
	WEATHER_TYPE_DELETE = 'WEATHER_TYPE_DELETE'
	WEATHER_TYPE_LIST = 'WEATHER_TYPE_LIST'
	WEATHER_TYPE_DETAILS = 'WEATHER_TYPE_DETAILS'

	# PRODUCT PERMISSION
	PRODUCT_CREATE = 'PRODUCT_CREATE'
	PRODUCT_UPDATE = 'PRODUCT_UPDATE'
	PRODUCT_DELETE = 'PRODUCT_DELETE'
	PRODUCT_LIST = 'PRODUCT_LIST'
	PRODUCT_DETAILS = 'PRODUCT_DETAILS'

	# DISCOUNT PERMISSION
	DISCOUNT_CREATE = 'DISCOUNT_CREATE'
	DISCOUNT_UPDATE = 'DISCOUNT_UPDATE'
	DISCOUNT_DELETE = 'DISCOUNT_DELETE'
	DISCOUNT_LIST = 'DISCOUNT_LIST'
	DISCOUNT_DETAILS = 'DISCOUNT_DETAILS'

	# BRAND PERMISSION
	BRAND_CREATE = 'BRAND_CREATE'
	BRAND_UPDATE = 'BRAND_UPDATE'
	BRAND_DELETE = 'BRAND_DELETE'
	BRAND_LIST = 'BRAND_LIST'
	BRAND_DETAILS = 'BRAND_DETAILS'

	# CATEGORY PERMISSION
	CATEGORY_CREATE = 'CATEGORY_CREATE'
	CATEGORY_UPDATE = 'CATEGORY_UPDATE'
	CATEGORY_DELETE = 'CATEGORY_DELETE'
	CATEGORY_LIST = 'CATEGORY_LIST'
	CATEGORY_DETAILS = 'CATEGORY_DETAILS'

	# COLOR PERMISSION
	COLOR_CREATE = 'COLOR_CREATE'
	COLOR_UPDATE = 'COLOR_UPDATE'
	COLOR_DELETE = 'COLOR_DELETE'
	COLOR_LIST = 'COLOR_LIST'
	COLOR_DETAILS = 'COLOR_DETAILS'

	# PRODUCT_COLOR PERMISSION
	PRODUCT_COLOR_CREATE = 'PRODUCT_COLOR_CREATE'
	PRODUCT_COLOR_UPDATE = 'PRODUCT_COLOR_UPDATE'
	PRODUCT_COLOR_DELETE = 'PRODUCT_COLOR_DELETE'
	PRODUCT_COLOR_LIST = 'PRODUCT_COLOR_LIST'
	PRODUCT_COLOR_DETAILS = 'PRODUCT_COLOR_DETAILS'

	# SIZE PERMISSION
	SIZE_CREATE = 'SIZE_CREATE'
	SIZE_UPDATE = 'SIZE_UPDATE'
	SIZE_DELETE = 'SIZE_DELETE'
	SIZE_LIST = 'SIZE_LIST'
	SIZE_DETAILS = 'SIZE_DETAILS'

	# SIZE PERMISSION
	PRODUCT_SIZE_CREATE = 'PRODUCT_SIZE_CREATE'
	PRODUCT_SIZE_UPDATE = 'PRODUCT_SIZE_UPDATE'
	PRODUCT_SIZE_DELETE = 'PRODUCT_SIZE_DELETE'
	PRODUCT_SIZE_LIST = 'PRODUCT_SIZE_LIST'
	PRODUCT_SIZE_DETAILS = 'PRODUCT_SIZE_DETAILS'

	# PRODUCT_IMAGE PERMISSION
	PRODUCT_IMAGE_CREATE = 'PRODUCT_IMAGE_CREATE'
	PRODUCT_IMAGE_UPDATE = 'PRODUCT_IMAGE_UPDATE'
	PRODUCT_IMAGE_DELETE = 'PRODUCT_IMAGE_DELETE'
	PRODUCT_IMAGE_LIST = 'PRODUCT_IMAGE_LIST'
	PRODUCT_IMAGE_DETAILS = 'PRODUCT_IMAGE_DETAILS'




