from enum import Enum


class PermissionEnum(Enum):

# ENUM FOR 'PRODUCT' APP
# 	
	# PRODUCT PERMISSION
	PRODUCT_CREATE = 'PRODUCT_CREATE'
	PRODUCT_UPDATE = 'PRODUCT_UPDATE'
	PRODUCT_DELETE = 'PRODUCT_DELETE'
	PRODUCT_LIST = 'PRODUCT_LIST'
	PRODUCT_DETAILS = 'PRODUCT_DETAILS'

	# PRODUCT_TAG PERMISSION
	PRODUCT_TAG_CREATE = 'PRODUCT_TAG_CREATE'
	PRODUCT_TAG_UPDATE = 'PRODUCT_TAG_UPDATE'
	PRODUCT_TAG_DELETE = 'PRODUCT_TAG_DELETE'
	PRODUCT_TAG_LIST = 'PRODUCT_TAG_LIST'
	PRODUCT_TAG_DETAILS = 'PRODUCT_TAG_DETAILS'

	# BRAND PERMISSION
	BRAND_CREATE = 'BRAND_CREATE'
	BRAND_UPDATE = 'BRAND_UPDATE'
	BRAND_DELETE = 'BRAND_DELETE'
	BRAND_LIST = 'BRAND_LIST'
	BRAND_DETAILS = 'BRAND_DETAILS'

	# CATEGORY PERMISSION
	CATEGORY_CREATE = 'CATEGORY_CREATE'
	CATEGORY_UPDATE = 'CATEGORY_UPDATE'
	CATEGORY_DELETE = 'CATEGORY_DELETE'
	CATEGORY_LIST = 'CATEGORY_LIST'
	CATEGORY_DETAILS = 'CATEGORY_DETAILS'

	# MANUFACTURER PERMISSION
	MANUFACTURER_CREATE = 'MANUFACTURER_CREATE'
	MANUFACTURER_UPDATE = 'MANUFACTURER_UPDATE'
	MANUFACTURER_DELETE = 'MANUFACTURER_DELETE'
	MANUFACTURER_LIST = 'MANUFACTURER_LIST'
	MANUFACTURER_DETAILS = 'MANUFACTURER_DETAILS'


	# COLOR PERMISSION
	COLOR_CREATE = 'COLOR_CREATE'
	COLOR_UPDATE = 'COLOR_UPDATE'
	COLOR_DELETE = 'COLOR_DELETE'
	COLOR_LIST = 'COLOR_LIST'
	COLOR_DETAILS = 'COLOR_DETAILS'


	# SIZE PERMISSION
	SIZE_CREATE = 'SIZE_CREATE'
	SIZE_UPDATE = 'SIZE_UPDATE'
	SIZE_DELETE = 'SIZE_DELETE'
	SIZE_LIST = 'SIZE_LIST'
	SIZE_DETAILS = 'SIZE_DETAILS'


	# PRODUCT_IMAGE PERMISSION
	PRODUCT_IMAGE_CREATE = 'PRODUCT_IMAGE_CREATE'
	PRODUCT_IMAGE_UPDATE = 'PRODUCT_IMAGE_UPDATE'
	PRODUCT_IMAGE_DELETE = 'PRODUCT_IMAGE_DELETE'
	PRODUCT_IMAGE_LIST = 'PRODUCT_IMAGE_LIST'
	PRODUCT_IMAGE_DETAILS = 'PRODUCT_IMAGE_DETAILS'




