# Generated by Django 3.2.13 on 2022-07-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220702_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AlterField(
            model_name='country',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='lon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
